### ISSUE TITLE
Unable to find documentation on HTTP endpoint as a supported output

### ISSUE THREAD

**Issue by britton-from-notion** [hashicorp-forge/grove#47] opened 2024-06-09 21:35 UTC
Hey there! Love the project, just had a question about the currently supported outputs. In the documentation it says "[While some users may want collected logs to be written directly to a local filesystem, others may want to write logs to AWS’ S3, or perhaps sent over HTTP to an external service](https://hashicorp-forge.github.io/grove/internals.html#output)". 

I looked around the repository, examples, and documentation a bit to see if there were any examples of writing log events over http to an external service and didn't spot anything built out for this. It looked like [AWS S3 is supported out of the box](https://hashicorp-forge.github.io/grove/grove.outputs.html#module-grove.outputs.aws_s3), but I couldn't find docs for shipping events to an http endpoint. Curious if I just missed it or if this functionality isn't setup out of the box yet! 

Thanks again! 😊

**Comment by hcpadkins** [comment] 2024-06-10 11:59
Hey Britton,

Thank you for raising this issue!

I can confirm that the HTTP output plugin is not yet implemented, however, if you can provide a little bit of context around what you'd like to see we'd be happy to get this together and merged. Ultimately, although the documentation is only an example of what is possible, this is something Grove should support and that we'd like to support out of the box.

The planned design was to just POST collected logs to a configured endpoint as new-line delimited JSON in batches - similar to the S3 output method. If a non-200 reply was received, the batch would be retried and collection pointers only updated once the remote service returns a successful HTTP status.

Would this sort of thing be suitable for your use case, or is there another set of functionality you'd expect to see?

Thank you again for feedback, and raising this issue!

**Comment by britton-from-notion** [comment] 2024-06-10 21:07
Hey @hcpadkins!

Thanks for the quick, thorough reply on this. I think that approach would work for my use case. As long as grove could ship NDJSON, we could consume that pretty comfortably 😄

We can also consume via the current S3 output, it'd just offer us some more options if we had the ability to shoot straight from grove via http.

As far as functionality I'd expect or hope to see, pretty much exactly what you described would check the box!

**Comment by hcpadkins** [comment] 2024-06-11 12:46
Hey Britton,

Thank you for the reply, that's great to hear! I've just cut a pull-request which should add this functionality under https://github.com/hashicorp-forge/grove/pull/48, which is awaiting internal review. Once reviewed and approved, a it will be merged and a new 0.4.0 release cut and published to PyPi.

That said, in the mean time, if you spot anything in the pull-request that looks like it may prevent your use of this output plugin please let me know.

Thanks again for raising this one!

**Comment by britton-from-notion** [comment] 2024-06-11 15:40
Wow you work quick! I took a look at the PR and it looks great to me. Solid unit test coverage, features matching your statements above, and some high quality maintainable code ✅ 

Thanks for your time and effort on this. Excited to give it a try once 1.4.0 drops!

**Comment by hcpadkins** [comment] 2024-06-14 09:35
Hey Britton,

v1.4.0 should now be available on PyPi which contains this new HTTP output module. I'll close this issue out for now, but if you encounter any issues please feel free to open a new Github issue and we can look into it further.

Thank you again for your issue, and your interest in Grove!

**Closed by hcpadkins** 2024-06-14 09:35 UTC
Labels: documentation, enhancement
