### ISSUE TITLE
Bug: Tines connector doesn't exit, leading to runaway tasks

### ISSUE THREAD

**Issue by britton-from-notion** [hashicorp-forge/grove#52] opened 2024-09-18 22:45 UTC
## Details

The Tines audit log connector doesn't appear to exit. It successfully pulls logs with no issues, but unlike the Okta connector, it will continue attempting to pull logs continuously. When using grove as a scheduled ECS task, this leads to overlapping runs of the grove container and an excess number of tasks running simultaneously. Additionally this leads to large spikes in NAT gateway traffic due to many concurrent duplicative data transfers, which is notoriously pretty expensive.

Looking at [the code for the tines connector](https://github.com/hashicorp-forge/grove/blob/285236965163bb0e78cc8771b86605bee1323b8a/grove/connectors/tines/api.py#L86C4-L117C10), I'm struggling to see what might be wrong here. The most likely culprit to me is something going wrong with the pagination. Although nothing appears out of the ordinary between grove's connector and [the Tines API docs for audit log listing](https://www.tines.com/api/audit-logs/list/#request).

Would love any help you can offer on this one! Thanks!

## Reference

![image](https://github.com/user-attachments/assets/67635014-c586-4451-8efc-aed3daf01e95)
![image](https://github.com/user-attachments/assets/52d3141b-c0be-4a04-aa24-bacb4b2358c4)
![image](https://github.com/user-attachments/assets/4b1d3ffc-6d98-439f-be1a-d1ef02c47f6a)

**Comment by hcpadkins** [comment] 2024-09-19 13:58
Hey there,

Thank you for the report! I'll have a look into this one and get back to you.

**Comment by britton-from-notion** [comment] 2024-09-25 21:57
Hey @hcpadkins, just followin up to see if you had any discoveries on this? 🙏

**Comment by hcpadkins** [comment] 2024-09-26 09:13
Hey again @britton-from-notion ,

Sorry for the delay on this one. I'm digging into this again today but I will let you know if I need any more information to help with triage.

**Comment by hcpadkins** [comment] 2024-09-26 15:12
Hey @britton-from-notion ,

Are you able to share your redacted connector configuration for this connector? Additionally, are you seeing any errors at all in the logs, or seeing the container exit uncleanly, or just running away?

As you suggest, we paginate based on the presence of a field in the [response from the Tines API](https://github.com/hashicorp-forge/grove/blob/285236965163bb0e78cc8771b86605bee1323b8a/grove/connectors/tines/api.py#L115). I'm wondering whether this has perhaps changed in some way, or if there is something more sinister going on.

You mentioned that the logs are being collected correctly, but are you able to check the value of the `_grove.pointer` and `_grove.previous_pointer` on some collected logs from two batches and see whether they are being correctly updated?

Unfortunately, it appears my test tenant for Tines no longer has the appropriate entitlements for audit logging so I'll need to get that sorted out before I can try and get a reproducer.

**Comment by jshlbrd** [comment] 2024-09-26 16:45
@hcpadkins I'm not sure if it's relevant but my team runs a similar tool to Grove and we also have a Tines audit API task, and we have seen this behavior in it (this is a comment pulled directly from our source code):
```
        # Tines returns events >= the `after` pagination cursor so we need to
        # increment this value to prevent duplicates.
```

We increment the `after` value, otherwise it can loop continuously and replay the same events over and over.

**Comment by britton-from-notion** [comment] 2024-09-26 17:42
Well hey stranger! @jshlbrd 👋 I'll give this a whirl first since its a pretty simple fix to try out.

@hcpadkins The following is usually what occurs after the number of concurrent tasks executing has increased to a pretty high number, upwards of 30+, then shortly after all the tines containers close out except the newest one. I do believe that there's something wrong with the pagination due to the fact that at not point does the tines connector notice "no more logs, therefore I should stop", it just keeps requesting. The lock not stopping the containers from running simultaneously feels like a potentially separate issue. Could be wrong, but that's my initial read.

Redacted logs
```
September 26, 2024 at 10:10 (UTC-7:00) | {"level": "ERROR", "location": "/usr/local/lib/python3.9/site-packages/grove/connectors/__init__.py:171", "message": "Connector 'grove.connectors.tines.audit_logs' could not complete collection successfully.", "timestamp": "2024-09-26 17:10:42,184+0000", "function": "run", "service": "grove", "detail": {"exception": "Valid lock already held and does not expire until 2024-09-26 17:15:38.289646", "operation": "all", "connector": "grove.connectors.tines.audit_logs", "identity": "redact"}, "context": {"runtime": "/usr/local/lib/python3.9/site-packages/grove/entrypoints/local_process.py", "runtime_id": "1", "runtime_host": "redact"}} | grove-container
September 26, 2024 at 10:10 (UTC-7:00) | {"level": "WARNING", "location": "/usr/local/lib/python3.9/site-packages/grove/connectors/__init__.py:162", "message": "Connector 'grove.connectors.tines.audit_logs' may already be running in another location.", "timestamp": "2024-09-26 17:10:41,883+0000", "function": "run", "service": "grove", "detail": {"exception": "Valid lock already held and does not expire until 2024-09-26 17:15:38.289646", "operation": "all", "connector": "grove.connectors.tines.audit_logs", "identity": "redact"}, "context": {"runtime": "/usr/local/lib/python3.9/site-packages/grove/entrypoints/local_process.py", "runtime_id": "1", "runtime_host": "redact"}}
```

Redacted connector
```json
{
    "identity": "my-identity",
    "name": "tines-audit-logs",
    "connector": "tines_audit_logs",
    "secret": {
        "key": "my aws secrets manager path"
    }
}
```

**Comment by hcpadkins** [comment] 2024-09-27 11:48
Thanks for the note, @jshlbrd, it's much appreciated! 

@britton-from-notion thank you for the additional context, this is useful! If you're able to try the suggestion from @jshlbrd in your environment to see if it resolves the issue that would be great! I'm still working to get the appropriate entitlement on my demo / integration tenant.

Currently, locking is used as a guard to prevent accidental concurrent collection of data. As a result, the connectors will launch, and it won't be until they it tries to start collection that they it will realise there is currently a lock held.

I should note that in the next release of Grove, which is being actively worked on, there are improvements for running in a long-lived environment rather than periodic execution - such when running as a daemon, or in a long lived container. These should help to alleviate the issue you're seeing with multiple tasks spawning concurrently, as the main thread will instead look after dispatching tasks on a configurable interval and track to completion or error.

**Comment by britton-from-notion** [comment] 2024-09-27 20:53
I'm currently giving variations of this change a go to see if it remediates the issue. Haven't gotten it yet, but this is the gist. I sent it over to the tines friends too and they poked their engineering folks to take a peak with us 😄 So, possible they'll have some inside tips on what we might be missing here. 

```python
  ...
  log = client.list_audit_logs(
      after=self.pointer,
      cursor=cursor,
      operation_name=operation,
  )

  # Find the latest timestamp from the log entries and update the pointer.
  if log.entries:
      latest_timestamp = max(entry['created_at'] for entry in log.entries)
      latest_datetime = datetime.fromisoformat(latest_timestamp.rstrip('Z'))
      self.pointer = latest_datetime.isoformat(sep="T", timespec="seconds") + "Z"

  # Save this batch of log entries.
  self.save(log.entries)
  ... 
```

The long lived changes sound super helpful and I'd probably end up moving over to that once it comes out!

**Comment by britton-from-notion** [comment] 2024-09-27 21:31
Okay as far as I can tell, the above change did fix the issue where the lock wasn't being respected. So now only 1 grove container will run at a time, but that one grove container continues to try and fetch from the tines audit logs continuously despite there being no results. So there's potentially something about the conditional logic here that doesn't limit the retries when there are no entries or something up with the cursor being an unexpected value? It's like there's somehow no entries but also a cursor which would make it keep retrying, but fail to save.

**Comment by hcpadkins** [comment] 2024-09-30 16:09
Hey again!

Thanks to the people over at Tines, my integration tenant has been configured with the required entitlement again. I've run the connector this morning and I'm not able to reproduce this issue against this tenant. Even without changes to the code that is in the main branch, the connector exits without writing any new logs, as there are no new events after the latest pointer.

I wonder if it has to do with event load? As my integration tenant has basically no activity, where I would assume yours is quite active all of the time?

**Comment by britton-from-notion** [comment] 2024-09-30 18:18
Interesting! I noticed the last 7 day behavior and then also notice the request for logs after the pointer. 

Our tenant has pretty high event load because we've got lots of folks actively building in there so its totally possible. But that seems super odd that it would affect this specific issue since the connector is performing requests, skipping due to no new logs, and then trying again and never exiting gracefully.

This is a side issue, but I noticed it was pretty tough to troubleshoot this because I thought whenever I was building the container and rolling it out after tweaking that small bit of python I mentioned above, that my updated code was being deployed. BUT I noticed that the Dockerfile actually pip installs the PyPi released version of grove and thats likely why my changes were never rolling out. So it's prob been totally placebo affect for any changes having an effect (whoops) 😅 

Could we update that Dockerfile so that it build whats in the repository? Or do you kinda envision new users just making a repository with a copy of the terraform, connector configs, and the Dockerfile? (I know I'm gettin into a separate issue here related to onboarding onto Grove, but it did tangentially connect to my inability to debug the deployment with some changes).

**Comment by hcpadkins** [comment] 2024-10-01 11:51
Hey @britton-from-notion,

Thanks for the note! I've gone ahead and moved the Dockerfile in `main` to install from the checked-out sources, and also moved it across to Python 3.12 - as there should be some performance improvements between Python 3.9 and Python 3.12 as well. You should be able to pull from `main` and have these changes now.

The deduplication stage may be causing the message where logs are collected but no new data output. Grove performs some basic [hash based deduplication](https://github.com/hashicorp-forge/grove/blob/main/grove/connectors/__init__.py#L345) to try and avoid duplicating logs returned by services which do "ON or AFTER" style filtering - which would return logs inclusive of the pointer, rather than after.

However, this certainly doesn't explain why the connector never exits. I'm still working on seeing if I can get a reproducer with a higher event load in my test tenant, but if you discover anything in the mean time please let me know!

Thanks for your patience while we track this one down.

**Comment by hcpadkins** [comment] 2024-10-08 11:12
Hey again,

I've been trying to reproduce this again, with a script that makes changes to a Tines story every 300ms and then every 100ms. When running Grove several times while this script is running I'm still unable to replicate the behaviour reported where the connector never exits. 

Can I ask where you are storing pointers (cache backend), and how you have configured ECS to run the connector tasks periodically? Just in case there is some combination of plugins which trigger this issue.

Thank you again for your help!

**Comment by hcpadkins** [comment] 2024-10-08 16:38
Hey @britton-from-notion,

I've just cut a new Grove release which includes these fixes as part of v1.5.0. As the release process has complete, this should be available via PyPi now.

* Grove [v1.5.0](https://github.com/hashicorp-forge/grove/releases/tag/v1.5.0)

If you could let me know if this resolves your issue, and if so we'll look to close this one out :)

**Comment by britton-from-notion** [comment] 2024-10-08 17:17
@hcpadkins Yayyy! Thanks so much for the hard work on this. I really appreciate you all. I'll update right now and report back 🫡

**Closed** 2024-10-08 17:47 UTC
Labels: bug

**Comment by tuckner** [comment] 2024-10-30 19:07
Super to see this get worked out. Thanks Peter!

**Comment by hcpadkins** [comment] 2024-10-31 10:41
No bother at all @tuckner, thank you for the assist on the tenant! :)
